[tool.ruff]
target-version = "py38"

[tool.ruff.lint]
select = [
    "A",            # flake8-builtins
    "ARG",          # flake8-unused-arguments
    "B",            # flake8-bugbear
    "C4",           # flake8-comprehensions
    "C90",          # mccabe
    "DTZ",          # flake8-datetimez
    "E", "W",       # pycodestyle
    "EXE",          # flake8-executable
    "F",            # pyflakes
    "I",            # isort
    "ISC",          # flake8-implicit-str-concat
    "N",            # pep8-naming
    "PIE",          # flake8-pie
    "PLC", "PLE",   # pylint
    "RET",          # flake8-return
    "SIM",          # flake8-simplify
    "T10",          # flake8-debugger
    "T20",          # flake8-print
    "TID",          # flake8-tidy-imports
    "UP",           # pyupgrade
    "YTT",          # flake8-2020
]
